# Generated by Django 3.2.18 on 2023-03-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_total_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='metric',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
